import Providers from "@/componentsForProvider/Providers";
import Header from "@/views/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/views/layout/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dine Market",
  description: "Generated by Hashim",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ClerkProvider>
            <Header />

            <main className="max-w-screen-xl mx-auto  ">{children}</main>
            <Footer />
          </ClerkProvider>
        </Providers>
      </body>
    </html>
  );
}
